# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('kanji_total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.CharField(max_length=1, unique=True)),
                ('ordinal', models.SmallIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KanjiCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanji_count.Article')),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanji_count.Kanji')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='kanjicount',
            unique_together=set([('article', 'kanji')]),
        ),
    ]
