# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji_count', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='kanji_total',
            field=models.IntegerField(default=0),
        ),
    ]
